apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opa-gatekeeper
spec:
  releaseName: opa-gatekeeper
  chart:
    spec:
      # renovate: registryUrl=https://open-policy-agent.github.io/gatekeeper/charts
      chart: gatekeeper
      version: 3.9.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  interval: 0h5m0s
  install:
    replace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
    cleanupOnFail: true
  values:
    postInstall:
      labelNamespace:
        enabled: true
      controllerManager:
        exemptNamespaces:
          - flux-system
          - kube-system
          - kube-node-lease
          - kube-public
          - default
          - nginx
          - local-storage-path
